  - name: Installing podman
    package:
      name: "podman"
      state: present
    become: true
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Installing Docker
    import_tasks: ubuntu.yaml
    when: ansible_facts['os_family'] == 'Debian'    