workstations:
  hosts:
    host1:
      ansible_host: ec2-3-95-7-111.compute-1.amazonaws.com
      ansible_port: 22
      ansible_ssh_private_key_file: /Users/felixliang/Downloads/cp4d-ws.pem
      ansible_user: ubuntu
    