workstations:
  hosts:
    host1:
      ansible_host: 169.59.6.199
      ansible_port: 2223
      ansible_ssh_private_key_file: /Users/felixliang/Downloads/pem_ibmcloudvsi.pem
      ansible_user: itzuser
    