---
- name: Ping my hosts
  ansible.builtin.ping: 

- name: Show facts available on the system
  ansible.builtin.debug:
      var: ansible_facts['os_family']

- name: Install unzip on Debian
  ansible.builtin.apt: name=unzip state=present update_cache=yes
  become: true 
  when: ansible_facts['os_family'] == 'Debian'  

- name: Install unzip
  package: name=unzip state=present 
  become: true   
  when: ansible_facts['os_family'] == 'RedHat'  

- name: Install wget
  package: name=wget state=present 
  become: true   
  when: ansible_facts['os_family'] == 'RedHat'    
  